using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;
using WizardBeardStudio.Rgs.Auth;
using WizardBeardStudio.Rgs.Core;
using WizardBeardStudio.Rgs.Models;
using WizardBeardStudio.Rgs.Services;

namespace WizardBeardStudio.Rgs.Tests.Editor
{
    public sealed class RgsClientIdempotencyTests
    {
        [Test]
        public void PlaceWager_WhenAutoGenerateDisabledAndNoKey_ThrowsValidation()
        {
            var client = BuildClient(autoGenerateIdempotencyKey: false);

            Assert.ThrowsAsync<RgsValidationException>(async () =>
                await client.PlaceWagerAsync("slot-1", 100, "USD", null, CancellationToken.None));
        }

        [Test]
        public async Task PlaceWager_WhenAutoGenerateEnabled_CallsWageringAndSucceeds()
        {
            var client = BuildClient(autoGenerateIdempotencyKey: true);

            var result = await client.PlaceWagerAsync("slot-1", 100, "USD", null, CancellationToken.None);

            Assert.That(result.Success, Is.True);
            Assert.That(result.WagerId, Is.EqualTo("w-1"));
        }

        private static RgsClient BuildClient(bool autoGenerateIdempotencyKey)
        {
            var transport = new FakeTransport();
            var tokenStore = new InMemoryTokenStore();
            tokenStore.Save("access-token", "refresh-token", "player-1");

            var identity = new IdentityClient(transport, "dev-1", "ua", string.Empty);
            var auth = new RgsAuthService(identity, tokenStore);
            var sessions = new SessionsClient(transport, () => tokenStore.AccessToken, "player-1", "dev-1", "ua", string.Empty);
            var ledger = new LedgerClient(transport, () => tokenStore.AccessToken, "player-1", "dev-1", "ua", string.Empty);
            var wagering = new WageringClient(transport, () => tokenStore.AccessToken, "player-1", "dev-1", "ua", string.Empty);

            var config = new RgsClientConfig
            {
                autoGenerateIdempotencyKey = autoGenerateIdempotencyKey,
                playerId = "player-1",
                defaultGameId = "slot-1",
                baseUrl = "http://localhost:8080",
            };

            return new RgsClient(config, auth, sessions, ledger, wagering);
        }

        private sealed class FakeTransport : IRgsTransport
        {
            public Task<string> PostJsonAsync(string path, string jsonBody, IDictionary<string, string>? headers, CancellationToken cancellationToken)
            {
                if (path == "/v1/wagering/wagers")
                {
                    return Task.FromResult("{" +
                                           "\"meta\":{" +
                                           "\"requestId\":\"req-1\"," +
                                           "\"resultCode\":\"RESULT_CODE_OK\"," +
                                           "\"denialReason\":\"\"," +
                                           "\"serverTime\":\"2026-02-15T00:00:00Z\"}," +
                                           "\"wager\":{" +
                                           "\"wagerId\":\"w-1\"," +
                                           "\"status\":\"WAGER_STATUS_PENDING\"}}" );
                }

                return Task.FromResult("{" +
                                       "\"meta\":{" +
                                       "\"requestId\":\"req-x\"," +
                                       "\"resultCode\":\"RESULT_CODE_OK\"," +
                                       "\"denialReason\":\"\"," +
                                       "\"serverTime\":\"2026-02-15T00:00:00Z\"}}" );
            }

            public Task<string> GetJsonAsync(string path, IDictionary<string, string>? headers, CancellationToken cancellationToken)
            {
                return Task.FromResult("{" +
                                       "\"meta\":{" +
                                       "\"requestId\":\"req-g\"," +
                                       "\"resultCode\":\"RESULT_CODE_OK\"," +
                                       "\"denialReason\":\"\"," +
                                       "\"serverTime\":\"2026-02-15T00:00:00Z\"}}" );
            }
        }
    }
}
